/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as ConcertsTrendingImport } from './routes/concerts/trending'
import { Route as ConcertsCityImport } from './routes/concerts/$city'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ConcertsTrendingRoute = ConcertsTrendingImport.update({
  id: '/concerts/trending',
  path: '/concerts/trending',
  getParentRoute: () => rootRoute,
} as any)

const ConcertsCityRoute = ConcertsCityImport.update({
  id: '/concerts/$city',
  path: '/concerts/$city',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/concerts/$city': {
      id: '/concerts/$city'
      path: '/concerts/$city'
      fullPath: '/concerts/$city'
      preLoaderRoute: typeof ConcertsCityImport
      parentRoute: typeof rootRoute
    }
    '/concerts/trending': {
      id: '/concerts/trending'
      path: '/concerts/trending'
      fullPath: '/concerts/trending'
      preLoaderRoute: typeof ConcertsTrendingImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/concerts/$city': typeof ConcertsCityRoute
  '/concerts/trending': typeof ConcertsTrendingRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/concerts/$city': typeof ConcertsCityRoute
  '/concerts/trending': typeof ConcertsTrendingRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/concerts/$city': typeof ConcertsCityRoute
  '/concerts/trending': typeof ConcertsTrendingRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/concerts/$city' | '/concerts/trending'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/concerts/$city' | '/concerts/trending'
  id: '__root__' | '/' | '/about' | '/concerts/$city' | '/concerts/trending'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConcertsCityRoute: typeof ConcertsCityRoute
  ConcertsTrendingRoute: typeof ConcertsTrendingRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConcertsCityRoute: ConcertsCityRoute,
  ConcertsTrendingRoute: ConcertsTrendingRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/concerts/$city",
        "/concerts/trending"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/concerts/$city": {
      "filePath": "concerts/$city.tsx"
    },
    "/concerts/trending": {
      "filePath": "concerts/trending.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
